---
- name: >
    Debian | set_fact
      rabbitmq_supported_os: True
  set_fact:
    rabbitmq_supported_os: True

- name: Debian | Add rabbitmq's official repository's key
  apt_key: url={{ rabbitmq_signing_key_location }} state=present

- name: Debian | Add rabbitmq's official repository
  copy: src=rabbitmq.list dest=/etc/apt/sources.list.d/ backup=yes
  register: aptrepo

- name: Debian | Install rabbitmq-server package
  apt: name=rabbitmq-server state=present update_cache=yes