---
- name: >
    Debian | set_fact
      rabbitmq_supported_os: True
  set_fact:
    rabbitmq_supported_os: True

- name: Debian | add the official rabbitmq repository's key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Debian | add the official rabbitmq repository
  copy: src=rabbitmq.list dest=/etc/apt/sources.list.d/ backup=yes
  register: aptrepo

- name: Debian | refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: Debian | install rabbitmq-server
  apt: name=rabbitmq-server state=present