---
# tasks file for rabbitmq

- name: Include RedHat specific packages
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific packages
  include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check for unsupported target operating system
  fail:
    msg: "The operating system ({{ ansible_os_family }}) of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: rabbitmq_supported_os is not defined

- name: Generate the rabbitmq configuration
  template:
    src=rabbitmq.config.j2
    dest={{ rabbitmq_conf_path }}/rabbitmq.config
    owner={{ rabbitmq_user }}
    group={{ rabbitmq_group }}
    mode=0644
    backup=yes
  notify: reload rabbitmq-server

- include: ssl.yml
  when: rabbitmq_ssl

- include: plugins.yml

- name: Enable and start the rabbitmq service
  service: name=rabbitmq-server state=started enabled=true

- include: vhost.yml

- include: federation.yml
  when: rabbitmq_federation


