---
- name: >
    RedHat | set_fact
      rabbitmq_supported_os: True
  set_fact:
    rabbitmq_supported_os: True

- name: RedHat | Install erlang package
  yum: name=erlang state=latest

- name: RedHat | Install rabbitmq signing key
  rpm_key: state=present key={{ rabbitmq_signing_key_location }}

#Only RPM install is availible at this time.
- name: RedHat | Install rabbitmq rpm
  yum: name={{ rabbitmq_rpm_location }} state=present