---
- name: >
    RedHat | set_fact
      rabbitmq_supported_os: True
  set_fact:
    rabbitmq_supported_os: True

- name: RedHat | Create the repository for EPEL
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: RedHat | Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: RedHat | Install Erlang
  yum: name=erlang state=latest

- name: RedHat | Install RabbitMQ signing key
  rpm_key: state=present key={{ rabbitmq_signing_key_location }}

- name: RedHat | Install Rabbitmq rpm
  yum: name={{ rabbitmq_rpm_location }} state=present